# Generated by Django 3.2.3 on 2021-06-28 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_rename_message_adminmessage_admin_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmessage',
            old_name='order_number',
            new_name='ref_number',
        ),
        migrations.RenameField(
            model_name='ordermessage',
            old_name='order_number',
            new_name='ref_number',
        ),
    ]
