# Generated by Django 3.2.3 on 2021-06-30 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_rename_ordermessage_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminMessage',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
