# Generated by Django 3.2.3 on 2021-07-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_usermessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermessage',
            options={},
        ),
    ]
