# Generated by Django 3.2.3 on 2021-07-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_usermessage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
