# Generated by Django 3.2.3 on 2021-05-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_album_track_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_format',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.genre'),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.label'),
        ),
    ]
