# Generated by Django 3.2.3 on 2021-05-30 15:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_album_track_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
