# Generated by Django 3.2.3 on 2021-05-30 16:01

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_album_track_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='track_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=list, size=None),
        ),
    ]
