# Generated by Django 3.2.3 on 2021-05-31 16:26

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_album_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_format',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='album',
            name='track_list',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='artist',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
