# Generated by Django 3.2.3 on 2021-06-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210531_1626'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Product',
        ),
    ]
