# Generated by Django 3.2.3 on 2021-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='genre',
        ),
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(blank=True, null=True, to='products.Genre'),
        ),
    ]
