# Generated by Django 3.2.3 on 2021-06-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210604_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.ManyToManyField(blank=True, to='products.Genre'),
        ),
    ]
