# Generated by Django 3.2.3 on 2021-06-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='friendly_name',
            field=models.CharField(max_length=100),
        ),
    ]
