# Generated by Django 3.2.3 on 2021-06-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_artist_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='artist',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
