# Generated by Django 3.2.3 on 2021-06-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20210624_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='upvote_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
