# Generated by Django 3.2.3 on 2021-06-25 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_productreview_upvote_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['review_date']},
        ),
    ]
