# Generated by Django 3.2.3 on 2021-06-25 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_productreview_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-review_date']},
        ),
    ]
