# Generated by Django 3.2.3 on 2021-06-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_productreview_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
