# Generated by Django 3.2.3 on 2021-06-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_productreview_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendly_name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ManyToManyField(blank=True, to='products.Promotion'),
        ),
    ]
