# Generated by Django 3.2.3 on 2021-06-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20210626_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.SlugField(max_length=254),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.SlugField(),
        ),
    ]
