# Generated by Django 3.2.3 on 2021-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20210627_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='friendly_name',
            field=models.CharField(max_length=50),
        ),
    ]
