# Generated by Django 3.2.3 on 2021-06-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_genre_friendly_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='friendly_name',
            field=models.CharField(max_length=50),
        ),
    ]
