# Generated by Django 3.2.3 on 2021-07-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_promotion_friendly_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pre_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
