# Generated by Django 3.2.3 on 2021-07-22 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
