# Generated by Django 3.2.3 on 2021-07-23 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_productreview_upvote_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='pre_sale_price',
            new_name='pre_discount_price',
        ),
    ]
