# Generated by Django 3.2.3 on 2021-07-27 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_rename_pre_sale_price_product_pre_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Spaces not allowed!', regex='^[-a-z0-9_]+$')]),
        ),
    ]
