# Generated by Django 3.2.3 on 2021-07-27 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0034_auto_20210727_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2021, message='Year in format YYYY between 1900-2021'), django.core.validators.MinValueValidator(1900, message='Year in format YYYY between 1900-2021')]),
        ),
    ]
